apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
controllerManagerExtraArgs:
  horizontal-pod-autoscaler-use-rest-clients: "true"
  horizontal-pod-autoscaler-sync-period: "10s"
  node-monitor-grace-period: "10s"
apiServerExtraArgs:
  runtime-config: "api/all=true"
kubernetesVersion: "v1.12.3"
networking:
  #dnsDomain: cluster.local
  podSubnet: 192.168.0.0/16
# --pod-network-cidr:192.168.0.0/16
featureGates:
  CoreDNS: true