apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
apiServer:
  timeoutForControlPlane: 4m0s
  # runtime-config: "api/all=true" xxxx v1beta1
  # allow-privileged: "true" xxxx v1beta1
# controllerManager:
  # horizontal-pod-autoscaler-use-rest-clients: "true" xxxx 
  # horizontal-pod-autoscaler-sync-period: "10s" xxxx
  # node-monitor-grace-period: "10s" xxxx
  # allocate-node-cidrs: "true" # not required but highly recommended xxxx
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: ""
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
# imageRepository: k8s.gcr.io
networking:
  # dnsDomain: cluster.local
  podSubnet: "10.0.0.0/8"
  # serviceSubnet: 10.96.0.0/12
# scheduler: {}